/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import { Map } from '../components/Map'
import { useJsApiLoader } from '@react-google-maps/api'
import { Navbar } from '../components/NavBar'

const API_KEY = process.env.NEXT_PUBLIC_API_KEY

const defaultCenter = {
    lat: 48.1351,
    lng: 11.582,
}

const libraries = ['places']

export default function Home() {
    const { isLoaded } = useJsApiLoader({
        id: 'google-map-script',
        googleMapsApiKey: API_KEY,
        libraries,
    })

    return (
        <>
            <Head>
                <title>Our project</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="keywords" content="next, javascript, js, react" />
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
                />

                <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" />
            </Head>
            <main>
                <header className="search">
                    <Navbar />
                    <form id="search-form" action="" method="get">
                        <i className="fas fa-search"></i>
                        <input
                            className="search-input"
                            id="search-input"
                            name="s"
                            placeholder="Choose your way..."
                            type="search"
                        />
                        <link
                            rel="stylesheet"
                            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css"
                        />
                        <button
                            className="submit"
                            id="search-button"
                            type="submit"
                        >
                            search
                        </button>
                    </form>
                </header>

                <div className="ourMap">
                    {isLoaded ? (
                        <Map center={defaultCenter} />
                    ) : (
                        <h2>Loading</h2>
                    )}
                </div>
            </main>
        </>
    )
}
