import Head from 'next/head'
const API_KEY = process.env.NEXT_PUBLIC_API_KEY

export default function Home() {
    return (
        <>
            <Head>
                <title>Our project</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="keywords" content="next, javascript, js, react" />
            </Head>
            <main>
                <div id="search">
                    <form id="search-form" action="" method="get">
                        <input
                            className="search"
                            id="search-input"
                            name="s"
                            placeholder="Choose your way..."
                            type="search"
                        />
                        <link
                            rel="stylesheet"
                            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css"
                        />
                        <button
                            className="submit"
                            id="search-button"
                            type="submit"
                        >
                            <i className="fas fa-search"></i>
                        </button>
                    </form>
                </div>
            </main>
        </>
    )
}
